/**
 * MelodyForge Studio - Instruments & Sound Design Library
 * Preset timbrici per simulare strumenti reali ed elettronici, con parametri DSP dedicati e pattern melodici.
 */

export const INSTRUMENT_PRESETS = [
  {
    id: "rave_supersaw",
    name: "⚡ Rave Supersaw Lead",
    category: "Lead & Synth",
    badge: "Anthem / Hardstyle",
    description: "Lead maestoso a più onde a dente di sega scordate (supersaw), stereofonico, brillante e potente.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: 0,
      osc1_detune: -7,
      osc1_volume: 0.8,
      osc2_wave: "sawtooth",
      osc2_octave: 0,
      osc2_detune: 8,
      osc2_volume: 0.8,
      sub_level: 0.35,
      noise_level: 0.05,
      unison_voices: 5,
      unison_detune: 22,
      unison_width: 0.85,
      filter_type: "lowpass",
      filter_cutoff: 4200,
      filter_resonance: 3.2,
      filter_env_amount: 3500,
      amp_attack: 0.008,
      amp_decay: 0.25,
      amp_sustain: 0.75,
      amp_release: 0.35,
      filter_attack: 0.005,
      filter_decay: 0.22,
      filter_sustain: 0.3,
      filter_release: 0.3,
      lfo_rate: 4.5,
      lfo_depth: 12,
      lfo_target: "pitch",
      lfo_wave: "sine",
      dist_drive: 0.25,
      chorus_mix: 0.45,
      delay_time: 0.375, // 3/16 sync approx
      delay_feedback: 0.35,
      delay_mix: 0.25,
      reverb_size: 0.7,
      reverb_decay: 2.2,
      reverb_mix: 0.35,
      eq_low: 1.0,
      eq_mid: 2.5,
      eq_high: 3.0,
      glide: 0.02
    }
  },
  {
    id: "hardstyle_screech",
    name: "🔥 Hardstyle Screech Lead",
    category: "Lead & Synth",
    badge: "Rawstyle / Hardcore",
    description: "Lead tagliente e aggressivo con armoniche esasperate e saturazione analogica per riff devastanti.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.9,
      osc2_wave: "square",
      osc2_octave: 1,
      osc2_detune: 14,
      osc2_volume: 0.8,
      sub_level: 0.2,
      noise_level: 0.12,
      unison_voices: 3,
      unison_detune: 28,
      unison_width: 0.7,
      filter_type: "bandpass",
      filter_cutoff: 2800,
      filter_resonance: 8.5,
      filter_env_amount: 4200,
      amp_attack: 0.003,
      amp_decay: 0.18,
      amp_sustain: 0.8,
      amp_release: 0.15,
      filter_attack: 0.002,
      filter_decay: 0.14,
      filter_sustain: 0.2,
      filter_release: 0.12,
      lfo_rate: 6.0,
      lfo_depth: 25,
      lfo_target: "cutoff",
      lfo_wave: "sawtooth",
      dist_drive: 0.65,
      chorus_mix: 0.2,
      delay_time: 0.25,
      delay_feedback: 0.4,
      delay_mix: 0.2,
      reverb_size: 0.5,
      reverb_decay: 1.5,
      reverb_mix: 0.25,
      eq_low: -2.0,
      eq_mid: 5.0,
      eq_high: 4.0,
      glide: 0.05
    }
  },
  {
    id: "trance_pluck",
    name: "💧 EDM / Trance Pluck",
    category: "Pluck & Percussive",
    badge: "Progressive / Melodic",
    description: "Pizzicato sintetico percussivo, attacco ultrarapido e delay stereofonico ipnotico.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: 0,
      osc1_detune: -5,
      osc1_volume: 0.85,
      osc2_wave: "triangle",
      osc2_octave: 1,
      osc2_detune: 6,
      osc2_volume: 0.65,
      sub_level: 0.1,
      noise_level: 0.08,
      unison_voices: 3,
      unison_detune: 12,
      unison_width: 0.6,
      filter_type: "lowpass",
      filter_cutoff: 1200,
      filter_resonance: 4.5,
      filter_env_amount: 5500,
      amp_attack: 0.002,
      amp_decay: 0.22,
      amp_sustain: 0.08,
      amp_release: 0.25,
      filter_attack: 0.001,
      filter_decay: 0.18,
      filter_sustain: 0.05,
      filter_release: 0.2,
      lfo_rate: 2.0,
      lfo_depth: 5,
      lfo_target: "none",
      lfo_wave: "sine",
      dist_drive: 0.15,
      chorus_mix: 0.35,
      delay_time: 0.375,
      delay_feedback: 0.55,
      delay_mix: 0.4,
      reverb_size: 0.75,
      reverb_decay: 2.5,
      reverb_mix: 0.35,
      eq_low: -1.0,
      eq_mid: 1.5,
      eq_high: 3.5,
      glide: 0.0
    }
  },
  {
    id: "grand_piano",
    name: "🎹 Grand Piano / Tasti Armonici",
    category: "Acoustic & Keys",
    badge: "Keys / Melodic",
    description: "Simulazione polifonica di pianoforte acustico/elettrico con transienti d'attacco e corpo caldo.",
    params: {
      osc1_wave: "triangle",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.9,
      osc2_wave: "sine",
      osc2_octave: 1,
      osc2_detune: 3,
      osc2_volume: 0.5,
      sub_level: 0.4,
      noise_level: 0.06,
      unison_voices: 2,
      unison_detune: 4,
      unison_width: 0.5,
      filter_type: "lowpass",
      filter_cutoff: 3400,
      filter_resonance: 1.8,
      filter_env_amount: 2800,
      amp_attack: 0.004,
      amp_decay: 0.6,
      amp_sustain: 0.25,
      amp_release: 0.5,
      filter_attack: 0.003,
      filter_decay: 0.4,
      filter_sustain: 0.15,
      filter_release: 0.4,
      lfo_rate: 1.5,
      lfo_depth: 4,
      lfo_target: "amp",
      lfo_wave: "sine",
      dist_drive: 0.05,
      chorus_mix: 0.25,
      delay_time: 0.25,
      delay_feedback: 0.2,
      delay_mix: 0.15,
      reverb_size: 0.8,
      reverb_decay: 2.8,
      reverb_mix: 0.38,
      eq_low: 2.0,
      eq_mid: 0.5,
      eq_high: 2.0,
      glide: 0.0
    }
  },
  {
    id: "rhodes_keys",
    name: "✨ Warm Rhodes E-Piano",
    category: "Acoustic & Keys",
    badge: "Deep / Chill / LoFi",
    description: "Pianoforte elettrico vintage stile Rhodes con suono dolce e campane armoniche calde.",
    params: {
      osc1_wave: "sine",
      osc1_octave: 0,
      osc1_detune: -2,
      osc1_volume: 0.95,
      osc2_wave: "triangle",
      osc2_octave: 0,
      osc2_detune: 4,
      osc2_volume: 0.6,
      sub_level: 0.3,
      noise_level: 0.02,
      unison_voices: 2,
      unison_detune: 6,
      unison_width: 0.7,
      filter_type: "lowpass",
      filter_cutoff: 2400,
      filter_resonance: 1.2,
      filter_env_amount: 1200,
      amp_attack: 0.006,
      amp_decay: 0.55,
      amp_sustain: 0.3,
      amp_release: 0.45,
      filter_attack: 0.005,
      filter_decay: 0.35,
      filter_sustain: 0.2,
      filter_release: 0.35,
      lfo_rate: 3.5,
      lfo_depth: 18,
      lfo_target: "amp",
      lfo_wave: "sine",
      dist_drive: 0.08,
      chorus_mix: 0.5,
      delay_time: 0.333,
      delay_feedback: 0.3,
      delay_mix: 0.25,
      reverb_size: 0.65,
      reverb_decay: 2.0,
      reverb_mix: 0.3,
      eq_low: 3.0,
      eq_mid: -1.0,
      eq_high: 1.5,
      glide: 0.0
    }
  },
  {
    id: "dark_techno_pad",
    name: "🌌 Dark Techno Pad & Strings",
    category: "Pad & Atmosphere",
    badge: "Hypnotic / Ambient",
    description: "Tappeto armonico avvolgente, attacco morbido, chorus lussureggiante e riverbero cattedrale.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: 0,
      osc1_detune: -8,
      osc1_volume: 0.75,
      osc2_wave: "sawtooth",
      osc2_octave: 0,
      osc2_detune: 9,
      osc2_volume: 0.75,
      sub_level: 0.4,
      noise_level: 0.08,
      unison_voices: 5,
      unison_detune: 18,
      unison_width: 0.95,
      filter_type: "lowpass",
      filter_cutoff: 1800,
      filter_resonance: 2.2,
      filter_env_amount: 1400,
      amp_attack: 0.45,
      amp_decay: 0.8,
      amp_sustain: 0.85,
      amp_release: 0.9,
      filter_attack: 0.5,
      filter_decay: 0.7,
      filter_sustain: 0.6,
      filter_release: 0.85,
      lfo_rate: 0.8,
      lfo_depth: 350,
      lfo_target: "cutoff",
      lfo_wave: "sine",
      dist_drive: 0.1,
      chorus_mix: 0.6,
      delay_time: 0.5,
      delay_feedback: 0.45,
      delay_mix: 0.35,
      reverb_size: 0.95,
      reverb_decay: 4.5,
      reverb_mix: 0.55,
      eq_low: 2.0,
      eq_mid: -0.5,
      eq_high: 2.5,
      glide: 0.08
    }
  },
  {
    id: "acid_303_lead",
    name: "🧪 Acid 303 Screamer Lead",
    category: "Lead & Synth",
    badge: "Acid / Rave 90s",
    description: "Sintetizzatore acido ad altissima risonanza, inviluppo rapido ed escursione dinamica del filtro.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.95,
      osc2_wave: "square",
      osc2_octave: 0,
      osc2_detune: 0,
      osc2_volume: 0.4,
      sub_level: 0.1,
      noise_level: 0.03,
      unison_voices: 1,
      unison_detune: 0,
      unison_width: 0.3,
      filter_type: "lowpass",
      filter_cutoff: 950,
      filter_resonance: 14.5,
      filter_env_amount: 5200,
      amp_attack: 0.003,
      amp_decay: 0.22,
      amp_sustain: 0.15,
      amp_release: 0.2,
      filter_attack: 0.002,
      filter_decay: 0.18,
      filter_sustain: 0.1,
      filter_release: 0.18,
      lfo_rate: 3.2,
      lfo_depth: 180,
      lfo_target: "cutoff",
      lfo_wave: "triangle",
      dist_drive: 0.55,
      chorus_mix: 0.15,
      delay_time: 0.25,
      delay_feedback: 0.4,
      delay_mix: 0.3,
      reverb_size: 0.45,
      reverb_decay: 1.4,
      reverb_mix: 0.22,
      eq_low: 0.0,
      eq_mid: 3.5,
      eq_high: 2.5,
      glide: 0.06
    }
  },
  {
    id: "cyberpunk_brass",
    name: "🎺 Cyberpunk Synth Brass",
    category: "Acoustic & Keys",
    badge: "Epic / Dystopian",
    description: "Ottoni sintetici roboanti in stile Blade Runner / Vangelis, con attacco ricco di mordente.",
    params: {
      osc1_wave: "sawtooth",
      osc1_octave: -1,
      osc1_detune: -5,
      osc1_volume: 0.85,
      osc2_wave: "sawtooth",
      osc2_octave: 0,
      osc2_detune: 5,
      osc2_volume: 0.85,
      sub_level: 0.4,
      noise_level: 0.04,
      unison_voices: 3,
      unison_detune: 15,
      unison_width: 0.75,
      filter_type: "lowpass",
      filter_cutoff: 1600,
      filter_resonance: 3.8,
      filter_env_amount: 3800,
      amp_attack: 0.08,
      amp_decay: 0.35,
      amp_sustain: 0.7,
      amp_release: 0.4,
      filter_attack: 0.06,
      filter_decay: 0.3,
      filter_sustain: 0.45,
      filter_release: 0.35,
      lfo_rate: 4.8,
      lfo_depth: 8,
      lfo_target: "pitch",
      lfo_wave: "sine",
      dist_drive: 0.35,
      chorus_mix: 0.3,
      delay_time: 0.375,
      delay_feedback: 0.35,
      delay_mix: 0.25,
      reverb_size: 0.85,
      reverb_decay: 3.2,
      reverb_mix: 0.4,
      eq_low: 3.5,
      eq_mid: 2.0,
      eq_high: 1.5,
      glide: 0.04
    }
  },
  {
    id: "crystal_bells",
    name: "🔔 FM Crystal Bells / Celesta",
    category: "Pluck & Percussive",
    badge: "Melodic / Ethereal",
    description: "Campane cristalline ed armoniche metalliche scintillanti con decadimento lungo.",
    params: {
      osc1_wave: "sine",
      osc1_octave: 1,
      osc1_detune: 0,
      osc1_volume: 0.85,
      osc2_wave: "square",
      osc2_octave: 2,
      osc2_detune: 14,
      osc2_volume: 0.3,
      sub_level: 0.0,
      noise_level: 0.05,
      unison_voices: 2,
      unison_detune: 6,
      unison_width: 0.8,
      filter_type: "bandpass",
      filter_cutoff: 3600,
      filter_resonance: 4.2,
      filter_env_amount: 2200,
      amp_attack: 0.002,
      amp_decay: 0.7,
      amp_sustain: 0.1,
      amp_release: 0.8,
      filter_attack: 0.001,
      filter_decay: 0.5,
      filter_sustain: 0.05,
      filter_release: 0.6,
      lfo_rate: 5.5,
      lfo_depth: 10,
      lfo_target: "pitch",
      lfo_wave: "sine",
      dist_drive: 0.05,
      chorus_mix: 0.4,
      delay_time: 0.333,
      delay_feedback: 0.5,
      delay_mix: 0.4,
      reverb_size: 0.9,
      reverb_decay: 3.8,
      reverb_mix: 0.45,
      eq_low: -2.0,
      eq_mid: 1.0,
      eq_high: 5.0,
      glide: 0.0
    }
  },
  {
    id: "chiptune_8bit",
    name: "👾 8-Bit Arcade Chiptune",
    category: "Lead & Synth",
    badge: "Retro / GameBoy",
    description: "Suono arcade puro ad onda quadra con attacco istantaneo per arpeggi fulminei e melodie retrò.",
    params: {
      osc1_wave: "square",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.9,
      osc2_wave: "square",
      osc2_octave: 1,
      osc2_detune: 0,
      osc2_volume: 0.4,
      sub_level: 0.2,
      noise_level: 0.04,
      unison_voices: 1,
      unison_detune: 0,
      unison_width: 0.0,
      filter_type: "lowpass",
      filter_cutoff: 8000,
      filter_resonance: 1.0,
      filter_env_amount: 0,
      amp_attack: 0.001,
      amp_decay: 0.15,
      amp_sustain: 0.4,
      amp_release: 0.05,
      filter_attack: 0.001,
      filter_decay: 0.1,
      filter_sustain: 1.0,
      filter_release: 0.05,
      lfo_rate: 8.0,
      lfo_depth: 0,
      lfo_target: "pitch",
      lfo_wave: "square",
      dist_drive: 0.2,
      chorus_mix: 0.0,
      delay_time: 0.1875,
      delay_feedback: 0.35,
      delay_mix: 0.25,
      reverb_size: 0.3,
      reverb_decay: 0.8,
      reverb_mix: 0.15,
      eq_low: 0.0,
      eq_mid: 2.0,
      eq_high: 2.0,
      glide: 0.0
    }
  },
  {
    id: "wood_marimba",
    name: "🪵 Wooden Mallet / Marimba",
    category: "Pluck & Percussive",
    badge: "Percussive / Melodic",
    description: "Percussione melodica in legno naturale con transiente deciso e risonanza organica.",
    params: {
      osc1_wave: "sine",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.95,
      osc2_wave: "triangle",
      osc2_octave: 2,
      osc2_detune: 0,
      osc2_volume: 0.35,
      sub_level: 0.25,
      noise_level: 0.12,
      unison_voices: 1,
      unison_detune: 0,
      unison_width: 0.2,
      filter_type: "lowpass",
      filter_cutoff: 2800,
      filter_resonance: 2.5,
      filter_env_amount: 3200,
      amp_attack: 0.002,
      amp_decay: 0.28,
      amp_sustain: 0.02,
      amp_release: 0.2,
      filter_attack: 0.001,
      filter_decay: 0.15,
      filter_sustain: 0.05,
      filter_release: 0.15,
      lfo_rate: 2.0,
      lfo_depth: 0,
      lfo_target: "none",
      lfo_wave: "sine",
      dist_drive: 0.08,
      chorus_mix: 0.15,
      delay_time: 0.375,
      delay_feedback: 0.4,
      delay_mix: 0.3,
      reverb_size: 0.7,
      reverb_decay: 2.0,
      reverb_mix: 0.32,
      eq_low: 1.5,
      eq_mid: 3.0,
      eq_high: 0.5,
      glide: 0.0
    }
  },
  {
    id: "pan_flute",
    name: "🌬️ Ethereal Solo Flute / Pipe",
    category: "Acoustic & Keys",
    badge: "Melodic / Folk",
    description: "Flauto a canne etereo con soffio d'aria modulato e vibrato melodico emotivo.",
    params: {
      osc1_wave: "triangle",
      osc1_octave: 0,
      osc1_detune: 0,
      osc1_volume: 0.85,
      osc2_wave: "sine",
      osc2_octave: 1,
      osc2_detune: 4,
      osc2_volume: 0.5,
      sub_level: 0.15,
      noise_level: 0.18,
      unison_voices: 2,
      unison_detune: 8,
      unison_width: 0.5,
      filter_type: "lowpass",
      filter_cutoff: 2900,
      filter_resonance: 2.0,
      filter_env_amount: 1500,
      amp_attack: 0.045,
      amp_decay: 0.35,
      amp_sustain: 0.75,
      amp_release: 0.35,
      filter_attack: 0.04,
      filter_decay: 0.25,
      filter_sustain: 0.5,
      filter_release: 0.3,
      lfo_rate: 5.2,
      lfo_depth: 16,
      lfo_target: "pitch",
      lfo_wave: "sine",
      dist_drive: 0.05,
      chorus_mix: 0.3,
      delay_time: 0.375,
      delay_feedback: 0.45,
      delay_mix: 0.3,
      reverb_size: 0.85,
      reverb_decay: 3.2,
      reverb_mix: 0.45,
      eq_low: -1.0,
      eq_mid: 2.0,
      eq_high: 3.0,
      glide: 0.07
    }
  }
];

/**
 * Generatori di pattern melodici intonati
 */
export const MELODY_TEMPLATES = {
  euphoric_anthem: {
    name: "🏆 Inno Eufonico (Hardstyle/Trance)",
    description: "Melodia epica ascendente con climax potente e note lunghe di risoluzione.",
    generate(rootNote, scaleId, numSteps = 16) {
      // Gradi della scala: 0 = root, 2 = 3rd, 4 = 5th, 6 = 7th, 7 = octave
      const degrees = [0, 0, 2, 4, 3, 2, 4, 7, 6, 4, 2, 3, 2, 0, 4, 0];
      return degrees.slice(0, numSteps);
    }
  },
  dark_techno_riff: {
    name: "⚡ Riff Dark Techno Ipnotico",
    description: "Pattern serrato e incalzante su poche note con rimbalzi ritmici e sincopi.",
    generate(rootNote, scaleId, numSteps = 16) {
      const degrees = [0, null, 1, 0, null, 0, 3, 0, null, 1, 0, null, 0, 4, 1, 0];
      return degrees.slice(0, numSteps);
    }
  },
  cyberpunk_arp: {
    name: "🌆 Arpeggio Cyberpunk Drive",
    description: "Cascata di arpeggi a sedicesimi perfetti per linee di piombo e synthwave.",
    generate(rootNote, scaleId, numSteps = 16) {
      const degrees = [0, 2, 4, 7, 4, 2, 7, 9, 7, 4, 2, 4, 0, 2, 4, 2];
      return degrees.slice(0, numSteps);
    }
  },
  acid_hook: {
    name: "🧪 Hook Acido 303 Groove",
    description: "Pattern sincopato con salti d'ottava e pause per far urlare la risonanza.",
    generate(rootNote, scaleId, numSteps = 16) {
      const degrees = [0, null, 0, 7, null, 3, 2, null, 0, null, 10, 7, null, 0, 3, 2];
      return degrees.slice(0, numSteps);
    }
  },
  ambient_harmony: {
    name: "🌌 Accordo Sostenuto & Tappeto",
    description: "Accordi e note lunghe di apertura per creare atmosfere cinematografiche.",
    generate(rootNote, scaleId, numSteps = 16) {
      const degrees = [0, null, null, null, 4, null, null, null, 2, null, null, null, 0, null, null, null];
      return degrees.slice(0, numSteps);
    }
  }
};
